config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resources :sessions, only:[:create]
  get '/signup', to:'users#new'
  get '/login', to:'sessions#new'
  delete '/logout', to: 'sessions#destroy'

  resources :relationships, only: [:create, :destroy]

  resources :categories

  resources :lessons do
    resources :answers
  end
  
  namespace :admin do
    resources :categories do
      resources :words
    end
    resources :users
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  has_many :words

  has_many :lessons
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :check_admin

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_url
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      redirect_to admin_categories_url
    else
      render 'edit'
    end
  end

  def destroy
    Category.find(params[:id]).destroy
    redirect_to admin_categories_url
  end

  def index
    # @categories = Category.all
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @words = @category.words
  end

  private
  def category_params
    params.require(:category).permit(:title, :description)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    # @categories = Category.all
    @categories = Category.paginate(page: params[:page], per_page: 6)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<div class="container-fluid pt-4 adminbg">
    <div class="d-flex align-content-center float-left flex-wrap  my-box-light" style="height: 40rem;">
        <div class="container admingamen">
            <h1 class="text-center">Edit Category</h1>
            <%= form_for([:admin, @category]) do |f| %>
                <%= f.label :title %>
                <%= f.text_field :title, class: "form-control" %>

                <%= f.label :description %>
                <%= f.text_field :description, class: "form-control"%>

                <%= f.submit "Save changes", class: "btn btn-block btn-flat-simple mt-4" %>
            <% end %>
            <%= link_to "<< Back", admin_categories_path, class: "aaa mt-4" %>
        </div>
    </div>
</div>

app/views/admin/categories/index.html.erb
<div class="container-fluid pt-4 indexbg">
    <div class="d-flex align-content-center float-left flex-wrap  my-box-light" style="height: 40rem;">
        <div class="container indexgamen">
            <h2 class="text-center">New Category</h2>
                <%= link_to "Create", new_admin_category_path, class: "btn btn-flat-simple btn-block mt-4" %>
        </div>
    </div>

    <div class="d-flex float-center flex-wrap my-box-light pt-5" style="height: 16rem;">            
        <table class="category_table table-responsive-md table-striped border border-dark">   
            <thead>
                <tr class="">
                    <td>Title</td>
                    <td>discription</td>
                    <td>Action</td>
                </tr>
            </thead>
            <tbody>
                <% @categories.each do |category| %>
                    <tr>
                        <td><%= category.title %></td>
                        <td><%= category.description %></td>
                        <td><%= link_to "Add", admin_category_path(category), class: "kk" %>/<%= link_to "Edit", edit_admin_category_path(category), class: "aaa" %>/<%= link_to 'Delete', admin_category_path(category), method: :delete,
                                                                                                                                data: { confirm: "Are you sure?" } %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
    <%= will_paginate %> 
</div>    

app/views/admin/categories/new.html.erb
<div class="container-fluid pt-4 adminbg">
    <div class="d-flex align-content-center float-left flex-wrap  my-box-light" style="height: 40rem;">
        <div class="container admingamen">
            <h3 class="text-center">New Category</h3>
            <%= form_for(:category, url: admin_categories_path) do |f| %>
                <%= f.label :title, class: "" %>
                <%= f.text_field :title, class: "form-control" %>

                <%= f.label :description, class: "" %>
                <%= f.text_field :description, class: "form-control description" %>

                <%= f.submit "submit", class: "btn btn-block btn-flat-simple mt-4" %>
            <% end %>
        </div>
    </div>    
</div>

app/views/admin/categories/show.html.erb
<div class="container-fluid pt-4 adminbg">
    <div class="d-flex align-content-center float-left flex-wrap  my-box-light" style="height: 40rem;">
        <div class="container admingamen">
            <h3 class="text-center">Word</h3>
            <%= @category.title %>
            <%= link_to "new word", new_admin_category_word_path(@category), class: "btn btn-block btn-flat-simple mt-4" %>
        </div>
    </div>    

    <div class="d-flex float-center flex-wrap my-box-light pt-5" style="height: 16rem;">            
        <table class="category_table table-responsive-md table-striped border border-dark">   
            <thead>
                <tr class="">
                    <td>Word</td>
                    <td>Answer</td>
                    <td>Action</td>
                </tr>
            </thead>
            <tbody>
                <% @words.each do |word| %>
                    <tr>
                        <td><%= word.content %></td>
                        <td><%= word.correct_answer %></td>
                        <td><%= link_to "Edit", edit_admin_category_word_path(@category, word), class: "aaa" %>/
                        <%= link_to 'Delete', admin_category_word_path(@category, word), method: :delete, data: { confirm: "Are you sure?" } %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>    