config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resources :sessions, only:[:create]
  get '/signup', to:'users#new'
  get '/login', to:'sessions#new'
  delete '/logout', to: 'sessions#destroy'

  resources :relationships, only: [:create, :destroy]

  resources :categories

  resources :lessons do
    resources :answers
  end
  
  namespace :admin do
    resources :categories do
      resources :words
    end
    resources :users
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  has_many :words

  has_many :lessons
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :check_admin

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_url
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      redirect_to admin_categories_url
    else
      render 'edit'
    end
  end

  def destroy
    Category.find(params[:id]).destroy
    redirect_to admin_categories_url
  end

  def index
    # @categories = Category.all
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @words = @category.words
  end

  private
  def category_params
    params.require(:category).permit(:title, :description)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    # @categories = Category.all
    @categories = Category.paginate(page: params[:page], per_page: 6)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<div class="container-fluid pt-4">
    <div class="container" style="width: 60%;">
        <h1 class="text-center pt-5">Lesson</h1>
        <div class="row">
            <% @categories.each do |category| %>
                <div class="col-6 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title"><%= category.title %></h5>
                            <p class="card-text"><%= category.description %></p>
                        <!-- <div class="text-right"><a href="/answers/new" class="btn btn-flat-simple">Start Lesson</a></div> -->
                        <% @lesson = current_user.took_lesson(category) %>
                        <% if @lesson.nil? %>
                            <%= button_to "Start Lesson", lessons_path(category_id: category.id), class:"btn btn-flat-simple" %>
                        <% else %>
                            <%= link_to "Show Result", lesson_path(@lesson), class:"btn btn-flat-simple" %>
                        <% end %>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
        <div class="pagenate text-center"><%= will_paginate %></div>
    </div>
</div>