config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resources :sessions, only:[:create]
  get '/signup', to:'users#new'
  get '/login', to:'sessions#new'
  delete '/logout', to: 'sessions#destroy'

  resources :relationships, only: [:create, :destroy]

  resources :categories

  resources :lessons do
    resources :answers
  end
  
  namespace :admin do
    resources :categories do
      resources :words
    end
    resources :users
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :action, polymorphic: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :lesson
  belongs_to :word
  belongs_to :choice
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  has_many :words

  has_many :lessons
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :word
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :answers
  has_many :words, through: :answers
  has_many :choices, through: :answers
  has_one :activity, as: :action, dependent: :destroy
  
  def next_word
    (category.words - words).first
  end

  def lesson_result
    choices.where(is_correct: true).count #get all choices where is_corerct is true
                                          #Count all choices where is_correct is true
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true

  has_one :activity, as: :action, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 6 }
  mount_uploader :avatar, AvatarUploader

  has_many :lessons

  def took_lesson(category)
    lessons.find_by(category: category)
  end

  has_many :active_relationships, class_name: "Relationship",foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed 
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :activities

  def follow(user)
    active_relationships.create(followed: user)
  end

  def unfollow(user)
    active_relationships.find_by(followed: user).destroy
  end

  def following?(user)
    following.include?(user)
  end
  
end

app/models/word.rb
class Word < ApplicationRecord
  validates :content, presence: true
  validates :choices, presence: true
  validate :has_one_correct
  validate :has_unique_choices

  belongs_to :category
  has_many :choices, dependent: :destroy
  accepts_nested_attributes_for :choices

  def correct_answer
    choices.find_by(is_correct: true).content
  end


  private
  def has_one_correct
    if choices.select {|choice| choice.is_correct == true}.count != 1
      return errors.add :base, "Must have one correct choice"
    end
  end

  def has_unique_choices
    if choices.uniq { |choice| choice.content }.count < choices.length
      return errors.add :base, "Must have unique choices"
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :check_admin

  def index
    # @users = User.all
    @users = User.paginate(page: params[:page], per_page: 7)
  end

  def update
    @user = User.find(params[:id])
    @user.update_attribute(:is_admin, true)
    
    redirect_to admin_users_url
  end

  def destroy
    @user = User.find(params[:id])
    @user.update_attribute(:is_admin, false)
    
    redirect_to admin_users_url
  end


end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def new
    @lesson = Lesson.find(params[:lesson_id])  
    @answer = Answer.new
    if @lesson.next_word.nil?
      @lesson.update(result: @lesson.lesson_result)
      @lesson.create_activity(user: current_user) #add later

      redirect_to lesson_url(@lesson) #in show page: @lesson.result
    end
  end

  def create
    @lesson = Lesson.find(params[:lesson_id])  
    @answer = @lesson.answers.create(answer_params)

    redirect_to new_lesson_answer_url(@lesson)
  end

  private
  def answer_params
   params.require(:answer).permit(:word_id, :choice_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private
  def check_admin
    unless current_user.is_admin?
      flash[:danger] = "You are not authorized"
      redirect_to root_url
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    # @categories = Category.all
    @categories = Category.paginate(page: params[:page], per_page: 6)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  def create
    @category = Category.find(params[:category_id])
    @lesson = @category.lessons.create(user:current_user)

    redirect_to new_lesson_answer_url(@lesson)

  end

  def show
    @lesson = Lesson.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:sessions][:email].downcase)

    if user && user.authenticate(params[:sessions][:password])
      log_in user
      redirect_to root_url #Goes to show page
    else
      render 'new'
    end
  end

#This is Sign out button
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @activities = @user.activities.where(user: @user).order(created_at: :desc).paginate(page: params[:page], per_page: 6)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    # @user = User.all
    @users = User.paginate(page: params[:page], per_page: 6)
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # logs in the given user 
  def log_in(user)
    session[:user_id] = user.id
  end
  #returns the currently logged_in user (if there is any logged_in user)
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  # Have a function to determine of tha user is logged in
  def logged_in?
    !current_user.nil?
  end
  #logs out current user
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  #returns the current loggedin user and
  #returns true is the given user is the current user
  def current_user?(user)
  user == current_user
  end

  # to avoid not logged-in users from making microposts
  def only_loggedin_users
    redirect_to login_url unless logged_in? # logged_in? is found in our SessionsHelper
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class="text-center mt-4">User Management</h1>
            <table class="table mt-3">   
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Admin</th>
                    </tr>
                </thead>
                <tbody>
                    <% @users.each do |user| %>
                        <tr>
                            <td><%= user.name %></td>
                            <td><%= user.email %></td>
                            <td>
                                <% if user.is_admin? %>
                                    <%= button_to "Remove", admin_user_path(user), method: :delete, class: "btn btn-secondary" %>
                                <% else %>
                                    <%= button_to "Add", admin_user_path(user), method: :patch, class: "btn btn-secondary" %>
                                <% end %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
    <div class="pagenate mt-1 text-center"><%= will_paginate %></div>
</div>

app/views/users/_follow_form.html.erb
<% if user != current_user %>
    <% if current_user.following?(user) %>
        <%= button_to "Unfollow", relationship_path(current_user.active_relationships.find_by(followed: user)), method: :delete, class: "btn btn-primary" %>
    <% else %>
        <%= button_to "Follow", relationships_path, params: {followed_id: user.id}, class: "btn btn-primary" %>
    <% end %>
<% end %>

app/views/users/_form.html.erb
<div class= "form">
    <%= form_for @user do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>

        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control"%>

        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control"%>

        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control"%>
        
        <%= f.label :avatar %>
        <%= f.file_field :avatar, class: "mt-2" %>

        <%= f.submit "Save changes", class: "btn btn-block btn-primary btnwidth" %>
    <% end %>
</div>

app/views/users/dashboard.html.erb
<div class="container mt-5">
    <div class="row">
        <aside class="col-4 text-center">
            <div class="card mt-5" style="width: 18rem;">
                <% if current_user.avatar.url %>
                    <%= image_tag current_user.avatar.url, size: 52, class: " text-center card-img" %>
                <% else %>
                    <i class="fa fa-user bigicon"></i>
                <% end %>
                <div class="card-body p-3">
                    <h3 class="card-title"><%= current_user.name %></h3>
                    <p class="card-text"><%= current_user.following.count %> following　<%= current_user.followers.count %> followers
                </div>
                <div class="card-body p-3">
                    <%= link_to "View my profile", current_user, class: "text-center btn btn-flat-simple-dash" %>
                    <%= link_to "Edit profile", edit_user_path(current_user), class:"btn btn-flat-simple-dash mr-1" %>
                </div>
            </div>
        </aside>        
        <div class="col-8 mt-5">
            <h2>activity Feed</h2>
            <% @activities.each do |activity| %>
                <div class="media">
                    <% if activity.user.avatar.url %>
                        <%= image_tag activity.user.avatar.url, size: 52, class: "card-img text-center" %>
                    <% else %>
                        <i class="fa fa-user icon"></i>
                    <% end %>
                    <div class="media-body">
                        <h5 class="mt-0">
                            <%= link_to (current_user == activity.user ? "You" : activity.user.name), activity.user %>
                            <% if activity.action_type == "Relationship" %>
                                followed <%= activity.action.followed.name %>
                            <% else %>
                                learned <%= activity.action.result %> of <%= activity.action.words.count %> in <%= link_to activity.action.category.title, activity.action %>
                            <% end %>
                        </h5>
                        <small class="text-muted">
                            <%= time_ago_in_words(activity.created_at) %>
                        </small>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<div class="container font-fix">
    <h1 class="text-center">Edit</h1>
    <%= form_for @user do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>

        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control"%>

        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control"%>

        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control"%>

        <%= f.label :avatar %>
        <%= f.file_field :avatar, class: "mt-2" %>

        <%= f.submit "Save changes", class: "btn btn-block btn-primary mt-4 btnwidth" %>
    <% end %>
</div>

app/views/users/index.html.erb
<div class="container-fluid pt-4">
    <div class="container" style="width: 60%;">
        <h1 class="text-center pt-5">List of Users</h1>
        <div class="row">
                <% @users.each do |user| %>
                    <div class="col-6 mb-4">
                        <div class="card">
                            <div class="card-body">
                                <% if user.avatar.url %>
                                    <%= image_tag user.avatar.url, size: 52, class: "card-img" %>
                                <% else %>
                                    <i class="fa fa-user icon"></i>
                                <% end %>
                                <%= link_to user.name, user %>
                                <%= render "follow_form", user: user %>
                            </div>
                        </div>
                    </div>
                <% end %>
        </div>
        <div class="pagenate text-center"><%= will_paginate %></div>
    </div>
</div>

app/views/users/new.html.erb
<div class="container font-fix">
    <h1 class="text-center text-black border-black">Sign up</h1>
    <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
    <div class="row">
        <aside class="col-4 text-center">
            <div class="card mt-5" style="width: 18rem;">
                <% if current_user.avatar.url %>
                    <%= image_tag current_user.avatar.url, size: 52, class: "card-img" %>
                <% else %>
                    <i class="fa fa-user bigicon"></i>
                <% end %>
                <div class="card-body p-3">
                    <h3 class="card-title"><%= current_user.name %></h3>
                    <p class="card-text"><%= current_user.following.count %> following　<%= current_user.followers.count %> followers
                </div>
            </div>
        </aside>        
        <div class="col-8 mt-5">
            <h2>activity Feed</h2>
            <% @activities.each do |activity| %>
                <div class="media">
                    <% if activity.user.avatar.url %>
                        <%= image_tag activity.user.avatar.url, size: 52, class: "card-img" %>
                    <% else %>
                        <i class="fa fa-user icon"></i>
                    <% end %>
                    <div class="media-body">
                        <h5 class="mt-0">
                            <%= link_to (current_user == activity.user ? "You" : activity.user.name), activity.user %>
                            <% if activity.action_type == "Relationship" %>
                                followed <%= activity.action.followed.name %>
                            <% else %>
                                learned <%= activity.action.result %> of <%= activity.action.words.count %> in <%= link_to activity.action.category.title, activity.action %>
                            <% end %>
                        </h5>
                        <small class="text-muted">
                            <%= time_ago_in_words(activity.created_at) %>
                        </small>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>