config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resources :sessions, only:[:create]
  get '/signup', to:'users#new'
  get '/login', to:'sessions#new'
  delete '/logout', to: 'sessions#destroy'

  resources :relationships, only: [:create, :destroy]

  resources :categories

  resources :lessons do
    resources :answers
  end
  
  namespace :admin do
    resources :categories do
      resources :words
    end
    resources :users
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :action, polymorphic: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :lesson
  belongs_to :word
  belongs_to :choice
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  has_many :words

  has_many :lessons
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :word
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :answers
  has_many :words, through: :answers
  has_many :choices, through: :answers
  has_one :activity, as: :action, dependent: :destroy
  
  def next_word
    (category.words - words).first
  end

  def lesson_result
    choices.where(is_correct: true).count #get all choices where is_corerct is true
                                          #Count all choices where is_correct is true
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true

  has_one :activity, as: :action, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 6 }
  mount_uploader :avatar, AvatarUploader

  has_many :lessons

  def took_lesson(category)
    lessons.find_by(category: category)
  end

  has_many :active_relationships, class_name: "Relationship",foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed 
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :activities

  def follow(user)
    active_relationships.create(followed: user)
  end

  def unfollow(user)
    active_relationships.find_by(followed: user).destroy
  end

  def following?(user)
    following.include?(user)
  end
  
end

app/models/word.rb
class Word < ApplicationRecord
  validates :content, presence: true
  validates :choices, presence: true
  validate :has_one_correct
  validate :has_unique_choices

  belongs_to :category
  has_many :choices, dependent: :destroy
  accepts_nested_attributes_for :choices

  def correct_answer
    choices.find_by(is_correct: true).content
  end


  private
  def has_one_correct
    if choices.select {|choice| choice.is_correct == true}.count != 1
      return errors.add :base, "Must have one correct choice"
    end
  end

  def has_unique_choices
    if choices.uniq { |choice| choice.content }.count < choices.length
      return errors.add :base, "Must have unique choices"
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def new
    @lesson = Lesson.find(params[:lesson_id])  
    @answer = Answer.new
    if @lesson.next_word.nil?
      @lesson.update(result: @lesson.lesson_result)
      @lesson.create_activity(user: current_user) #add later

      redirect_to lesson_url(@lesson) #in show page: @lesson.result
    end
  end

  def create
    @lesson = Lesson.find(params[:lesson_id])  
    @answer = @lesson.answers.create(answer_params)

    redirect_to new_lesson_answer_url(@lesson)
  end

  private
  def answer_params
   params.require(:answer).permit(:word_id, :choice_id)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  def create
    @category = Category.find(params[:category_id])
    @lesson = @category.lessons.create(user:current_user)

    redirect_to new_lesson_answer_url(@lesson)

  end

  def show
    @lesson = Lesson.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @activities = @user.activities.where(user: @user).order(created_at: :desc).paginate(page: params[:page], per_page: 6)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    # @user = User.all
    @users = User.paginate(page: params[:page], per_page: 6)
  end


  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # logs in the given user 
  def log_in(user)
    session[:user_id] = user.id
  end
  #returns the currently logged_in user (if there is any logged_in user)
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  # Have a function to determine of tha user is logged in
  def logged_in?
    !current_user.nil?
  end
  #logs out current user
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  #returns the current loggedin user and
  #returns true is the given user is the current user
  def current_user?(user)
  user == current_user
  end

  # to avoid not logged-in users from making microposts
  def only_loggedin_users
    redirect_to login_url unless logged_in? # logged_in? is found in our SessionsHelper
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="col-12">
        <div class="container">                    
            <div class="row">
                <div class="col-4 my-3 text-left text-secondary">
                © ︎All right reserved
                </div>
                <div class="col-8 my-3 text-right text-secondary">
                <i class="fa fa-facebook-square"></i>
                <i class="fa fa-twitter-square"></i>
                <i class="fa fa-instagram"></i>
                </div>
            </div>
        </div>    
    </div>   
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-light">

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <%#a class="nav-link text-secondary" href="/">Home <span class="sr-only">(current)</span></a> %>
                <%= link_to "Home", root_path, class: "nav-link text-secondary" %>
            </li>
            <% if logged_in? %>
            <li class="nav-item active">
                <a class="nav-link text-secondary" href="/categories">Lesson </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link text-secondary" href="/users">Users </a>
            </li>
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle text-secondary" data-toggle="dropdown">
                    <%= "Setting" %> <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><%= link_to "profile", current_user, class: "dropdown-item" %></li>
                        <li><%= link_to "settings", edit_user_path(current_user), class: "dropdown-item" %></li>
                        <li class="divider"></li>
                        <li>
                            <%= link_to "Sign out", logout_path, method: :delete, class: "dropdown-item" %>
                        </li>


                        <% if current_user.is_admin? %>
                            <li>
                                <%= link_to "Manage Categories", admin_categories_path, class: "dropdown-item" %>
                            </li>
                            <li>
                                <%= link_to "Manage Users", admin_users_path, class: "dropdown-item" %>
                            </li>
                        <% end %>
                    </ul>
                </li>
            <% else %>  
            <li class="nav-item">
                <%= link_to "Signup", signup_path, class: "nav-link text-secondary" %>    
            </li>
            <li class="nav-item">
                <%= link_to "Login", login_path, class: "nav-link text-secondary" %>
            </li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>ELearningYusuke</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link href="https://fonts.googleapis.com/css?family=Abel|Josefin+Sans|Sriracha|Varela+Round&display=swap" rel="stylesheet">
    </head>

    <body>
    
        <%= render 'layouts/header' %>
    
        <%= yield %>
    
        <%= render 'layouts/footer' %>

    </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="alert alert-danger">
        <div>
            <%= pluralize(object.errors.count, "error") %> prohibited this action:
        </div>
        <ul>
            <% object.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>